import os

# Configurable analysis thresholds for Suspicious Pattern Detection (Phase 5)
RAPID_TRANSFER_SECONDS: int = int(os.getenv("RAPID_TRANSFER_SECONDS", "900"))  # 15 minutes
FUND_SPLIT_MIN_DESTINATIONS: int = int(os.getenv("FUND_SPLIT_MIN_DESTINATIONS", "3"))
FUND_CONSOLIDATION_MIN_SOURCES: int = int(os.getenv("FUND_CONSOLIDATION_MIN_SOURCES", "3"))
HIGH_FREQUENCY_WINDOW_MINUTES: int = int(os.getenv("HIGH_FREQUENCY_WINDOW_MINUTES", "60"))
HIGH_FREQUENCY_TRANSACTION_COUNT: int = int(os.getenv("HIGH_FREQUENCY_TRANSACTION_COUNT", "10"))
BURST_TX_PER_MINUTE_THRESHOLD: float = float(os.getenv("BURST_TX_PER_MINUTE_THRESHOLD", "0.5"))
LARGE_TRANSFER_MULTIPLIER: float = float(os.getenv("LARGE_TRANSFER_MULTIPLIER", "3.0"))
LARGE_TRANSFER_MIN_ETH: float = float(os.getenv("LARGE_TRANSFER_MIN_ETH", "1.0"))
MAX_ANALYSIS_HOPS: int = int(os.getenv("MAX_ANALYSIS_HOPS", "5"))
CYCLE_DETECTION_MAX_LENGTH: int = int(os.getenv("CYCLE_DETECTION_MAX_LENGTH", "6"))
UNUSUAL_COUNTERPARTY_COUNT: int = int(os.getenv("UNUSUAL_COUNTERPARTY_COUNT", "8"))
